apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: add
spec:
  selector:
    matchLabels:
      app: add
  replicas: 1
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
        - name: hello-grpc-server
          image: hello-grpc-server:v0.0.1
          ports:
            - name: server-service
              containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: add
  ports:
    - port: 50051
      targetPort: server-service